### ISSUE TITLE
test: representative example for hop-plot

### ISSUE THREAD

**Issue by s-aguinaga** [kunegis/konect-toolbox#1]
I am new to net analysis using Matlab. Would you please provide an example of a toy-graph on which I can compute hop-plot?

I tried to the following and received errors:

> addpath ./m
>  addpath ./test
>  test_compute_map

and the error I get:

> Undefined function 'compute_map' for input arguments of type 'double'.

**Comment by kunegis** [comment]
Hello

The functions in konect-toolbox/test/ do not generate a hop plot.  For a hop plot (which in KONECT is called "hop distribution"), look at the files in the KONECT Analysis package:

https://github.com/kunegis/konect-analysis

In particular the files 

m/hopdistr_comp.m  which computes the data
and
m/hopdistr_plot.m which plots it

Best
Jérôme
