### ISSUE TITLE
Possible Mistakes in konect_statistic_fill.m

### ISSUE THREAD

**Issue by tangdale** [kunegis/konect-toolbox#3]
Dear Professor Kunegis,
         In konect_statistic_fill.m, n equals to "nnz(sum(A, 1)' + sum(A, 2))". However, this is not necessarily the number of nodes size(A). I attach my adjacent matrix in the question.

0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	0	0	0	0	0	0	1	1	0	0	0
0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	1	0	0	0	0	0	0	1	0	0	0
0	0	0	1	0	0	0	0	0	1	0	0	0	0
0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	0	0	0	0	0	0	0	0	0	0	0

**Comment by kunegis** [comment]
Hello

In KONECT, isolated nodes (i.e., nodes without neighbours) are not considered, i.e., they are ignored by all algorithms.  This makes a difference for elementary statistics such as the size (number of nodes) and the fill (edge probability), but is unproblematic for advanced statistics such as the clustering coefficient or spectral norm. 

Thus, the fill of the matrix given in the parent post should be returned as 1, if I'm not mistaken.

Best
Jérôme
